# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: A:/heap/Analysis_code/FPGA code/fpga_microblaze/fpga_microblaze.srcs/sources_1/bd/mb_test/ip/mb_test_ilmb_bram_if_cntlr_0/mb_test_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_test_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/heap/Analysis_code/FPGA code/fpga_microblaze/fpga_microblaze.srcs/sources_1/bd/mb_test/ip/mb_test_ilmb_bram_if_cntlr_0/mb_test_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_test_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: A:/heap/Analysis_code/FPGA code/fpga_microblaze/fpga_microblaze.srcs/sources_1/bd/mb_test/ip/mb_test_ilmb_bram_if_cntlr_0/mb_test_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_test_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/heap/Analysis_code/FPGA code/fpga_microblaze/fpga_microblaze.srcs/sources_1/bd/mb_test/ip/mb_test_ilmb_bram_if_cntlr_0/mb_test_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_test_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
