# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_test/mb_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test || ORIG_REF_NAME==mb_test} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_proc_sys_reset_0_0/mb_test_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_proc_sys_reset_0_0 || ORIG_REF_NAME==mb_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_clk_wiz_0_1/mb_test_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_clk_wiz_0_1 || ORIG_REF_NAME==mb_test_clk_wiz_0_1} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_microblaze_0_0/mb_test_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_microblaze_0_0 || ORIG_REF_NAME==mb_test_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_dlmb_v10_0/mb_test_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_dlmb_v10_0 || ORIG_REF_NAME==mb_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_ilmb_v10_0/mb_test_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_ilmb_v10_0 || ORIG_REF_NAME==mb_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_dlmb_bram_if_cntlr_0/mb_test_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_ilmb_bram_if_cntlr_0/mb_test_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_lmb_bram_0/mb_test_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_lmb_bram_0 || ORIG_REF_NAME==mb_test_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_mdm_1_0/mb_test_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_mdm_1_0 || ORIG_REF_NAME==mb_test_mdm_1_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_axi_uartlite_0_0/mb_test_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_axi_uartlite_0_0 || ORIG_REF_NAME==mb_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_test/ip/mb_test_microblaze_0_axi_periph_0/mb_test_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_test_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/mb_test/mb_test_ooc.xdc
